name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        mode: [release, dev]
        go: ["1.24"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pkg/deej/scripts/linux/build-${{ matrix.mode }}.sh
